### PR TITLE
fix(llm lookup): allow Tools to specify fallback LLMs in lookups

### LINKED ISSUE #415: SDK TextRewriteTool doesn't work in 2.17.3
In 2.17.3 the premade tool text_rewrite_tool gives error when trying to use it:

  

File "C:\Code\python\steamship\agent-starter\src\api.py", line 88, in prompt
    self.run_agent(self.incoming_message_agent, context)
  File "C:\Python311\Lib\site-packages\steamship\agents\service\agent_service.py", line 59, in run_agent
    self.run_action(action=action, context=context)
  File "C:\Python311\Lib\site-packages\steamship\agents\service\agent_service.py", line 25, in run_action
    blocks_or_task = action.tool.run(tool_input=action.input, context=context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\steamship\agents\tools\text_generation\text_rewrite_tool.py", line 52, in run
    output_blocks = llm.complete(prompt=prompt)
                    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'complete'

### PR DESCRIPTION
**Pull request by douglas-reid**
This provides our initial Tools with a "safer" way of getting an LLM as needed to perform their tasks.

Stylistically, there is a larger conversation to be had about the "right" way of passing LLMs to Tools, but this at least prevents  problematic usage with the existing pattern.

Fixes #415

### CODE REVIEW

**Comment by eob** [comment]
@douglas-reid i propose we consider this a green check and separately address the failed test.

It's basically testing something inherently probabilistic (embedding of various words + AKNN lookup) -- the "A" in "AKNN" being the element of stochastic behavior
