### ISSUE TITLE
SDK TextRewriteTool doesn't work in 2.17.3

### ISSUE THREAD

**Issue by MikPoik** [steamship-core/python-client#415]
In 2.17.3 the premade tool text_rewrite_tool gives error when trying to use it:

  

File "C:\Code\python\steamship\agent-starter\src\api.py", line 88, in prompt
    self.run_agent(self.incoming_message_agent, context)
  File "C:\Python311\Lib\site-packages\steamship\agents\service\agent_service.py", line 59, in run_agent
    self.run_action(action=action, context=context)
  File "C:\Python311\Lib\site-packages\steamship\agents\service\agent_service.py", line 25, in run_action
    blocks_or_task = action.tool.run(tool_input=action.input, context=context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\steamship\agents\tools\text_generation\text_rewrite_tool.py", line 52, in run
    output_blocks = llm.complete(prompt=prompt)
                    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'complete'

**Comment by douglas-reid** [comment]
@MikPoik I believe that is saying that `llm` is `None`. To use it in an agent, you need to set an LLM in the context.

Example (from the `main` in that tool): `context=with_llm(llm=OpenAI(client=client))`.

@eob this is related to your `get_or_default` question, earlier, I believe.

**Comment by eob** [comment]
@MikPoik thank you for catching this.

I think the tool __main__  methods fell out of sync with some of the changes in the base SDK and it didn't yet have unit test coverage to block the merge.

We're pushing some changes today to fix and will update you and close the issue when they're in.

Thanks again!
